name: search-engine
channels:
  - defaults
dependencies:
  - beautifulsoup4=4.14.2=py310hca03da5_0
  - brotlicffi=1.2.0.0=py310h50f4ffc_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - certifi=2025.11.12=py310hca03da5_0
  - cffi=2.0.0=py310h73c2a22_1
  - charset-normalizer=3.4.4=py310hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - idna=3.11=py310hca03da5_0
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - pycparser=2.23=py310hca03da5_0
  - pysocks=1.7.1=py310hca03da5_1
  - python=3.10.19=hf701271_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py310hca03da5_1
  - setuptools=80.9.0=py310hca03da5_0
  - soupsieve=2.5=py310hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=py310hca03da5_0
  - typing_extensions=4.15.0=py310hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py310hca03da5_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
prefix: /opt/miniconda3/envs/search-engine
